In [183]:
from tensorflow import keras 
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [184]:
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

In [185]:
import numpy as pandas

In [186]:
import cv2
from sklearn.linear_model import LinearRegression



In [187]:
(x_train , y_train), (x_test , y_test) = keras.datasets.cifar10.load_data()

In [188]:
x_train.shape,x_test.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

maintain the pixels of all the image we use normalization
 

In [189]:
# Normalization
x_train = x_train/255.0
x_test = x_test/255.0

In [190]:
# sklearn uses 2d array as input 
nsamples, nx, ny, nrgb = x_train.shape
x_train2 = x_train.reshape((nsamples,nx*ny*nrgb))

In [191]:
nsamples, nx, ny, nrgb = x_test.shape
x_test2 = x_test.reshape((nsamples,nx*ny*nrgb))

In [192]:
model=RandomForestClassifier()

In [193]:
model.fit(x_train2,y_train)


C:\Users\Aashi Kushwah\PycharmProjects\pythonProject\.venv\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [194]:
y_pred=model.predict(x_test2)
y_pred

array([6, 8, 8, ..., 3, 2, 7], dtype=uint8)

In [195]:
accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.55      0.53      0.54      1034
           1       0.55      0.52      0.53      1052
           2       0.32      0.38      0.34       839
           3       0.26      0.31      0.28       825
           4       0.40      0.40      0.40       989
           5       0.40      0.42      0.41       955
           6       0.57      0.47      0.52      1209
           7       0.46      0.51      0.48       893
           8       0.62      0.57      0.60      1083
           9       0.54      0.48      0.51      1121

    accuracy                           0.47     10000
   macro avg       0.47      0.46      0.46     10000
weighted avg       0.48      0.47      0.47     10000



In [196]:
confusion_matrix(y_pred,y_test)

array([[552,  35, 108,  51,  56,  36,  14,  45,  88,  49],
       [ 41, 547,  43,  45,  20,  24,  31,  43,  90, 168],
       [ 60,  12, 317,  66, 146,  86,  78,  50,  15,   9],
       [ 19,  40,  86, 259,  59, 158,  70,  69,  25,  40],
       [ 30,  24, 146,  85, 396,  69, 107,  96,  21,  15],
       [ 20,  23,  61, 200,  48, 403,  59,  81,  30,  30],
       [ 20,  42, 119, 136, 146,  78, 572,  49,  13,  34],
       [ 27,  28,  65,  61,  85,  84,  23, 459,  21,  40],
       [173,  71,  28,  26,  28,  27,   9,  22, 621,  78],
       [ 58, 178,  27,  71,  16,  35,  37,  86,  76, 537]], dtype=int64)

In [197]:
# here we can see by Randomforest classifier accuracy is 47%

NOW IMPLEMENTING KNN CLASSIFIER

In [198]:
from sklearn.neighbors import KNeighborsClassifier

In [199]:
knn=KNeighborsClassifier(n_neighbors=7)

In [200]:
knn.fit(x_train2,y_train)

C:\Users\Aashi Kushwah\PycharmProjects\pythonProject\.venv\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [201]:
y_pred_knn=knn.predict(x_test2)
y_pred_knn

array([2, 8, 8, ..., 5, 6, 4], dtype=uint8)

In [202]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.52      0.40      0.45      1299
           1       0.20      0.70      0.30       280
           2       0.44      0.22      0.29      2013
           3       0.20      0.28      0.23       707
           4       0.52      0.23      0.32      2222
           5       0.20      0.40      0.27       504
           6       0.27      0.35      0.30       761
           7       0.20      0.70      0.31       281
           8       0.69      0.39      0.50      1749
           9       0.14      0.73      0.23       184

    accuracy                           0.34     10000
   macro avg       0.34      0.44      0.32     10000
weighted avg       0.45      0.34      0.35     10000



In [203]:
confusion_matrix(y_pred_knn,y_test)

array([[518, 118, 110,  66,  60,  63,  22,  78, 112, 152],
       [  7, 195,   2,   5,   0,   2,   1,   8,  10,  50],
       [118, 124, 437, 243, 268, 225, 271, 185,  47,  95],
       [ 12,  51,  50, 199,  33, 156,  56,  57,  34,  59],
       [ 46, 173, 250, 214, 521, 201, 319, 294,  69, 135],
       [  5,  32,  24, 102,  14, 204,  32,  60,  12,  19],
       [ 30,  55,  65, 108,  44,  80, 265,  48,  14,  52],
       [  5,   8,   7,  11,  11,  10,   1, 196,   7,  25],
       [255, 223,  53,  51,  48,  53,  32,  68, 688, 278],
       [  4,  21,   2,   1,   1,   6,   1,   6,   7, 135]], dtype=int64)

In [204]:
#KNN Classifier shows only 34% accuracy 

IMPLEMENTING DECISION TREE

In [205]:
from sklearn.tree import DecisionTreeClassifier

In [206]:
dtc=DecisionTreeClassifier()

In [207]:
dtc.fit(x_train2,y_train)

DecisionTreeClassifier()

In [208]:
y_pred_dtc=dtc.predict(x_test2)
y_pred_dtc

array([7, 1, 9, ..., 2, 2, 1], dtype=uint8)

In [209]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_dtc,y_test))

              precision    recall  f1-score   support

           0       0.35      0.33      0.34      1063
           1       0.27      0.29      0.28       943
           2       0.22      0.21      0.22      1072
           3       0.18      0.18      0.18       999
           4       0.22      0.22      0.22      1033
           5       0.22      0.23      0.23       980
           6       0.27      0.27      0.27      1006
           7       0.26      0.28      0.27       947
           8       0.39      0.39      0.39      1006
           9       0.29      0.31      0.30       951

    accuracy                           0.27     10000
   macro avg       0.27      0.27      0.27     10000
weighted avg       0.27      0.27      0.27     10000



In [210]:
confusion_matrix(y_pred_knn,y_test)

array([[518, 118, 110,  66,  60,  63,  22,  78, 112, 152],
       [  7, 195,   2,   5,   0,   2,   1,   8,  10,  50],
       [118, 124, 437, 243, 268, 225, 271, 185,  47,  95],
       [ 12,  51,  50, 199,  33, 156,  56,  57,  34,  59],
       [ 46, 173, 250, 214, 521, 201, 319, 294,  69, 135],
       [  5,  32,  24, 102,  14, 204,  32,  60,  12,  19],
       [ 30,  55,  65, 108,  44,  80, 265,  48,  14,  52],
       [  5,   8,   7,  11,  11,  10,   1, 196,   7,  25],
       [255, 223,  53,  51,  48,  53,  32,  68, 688, 278],
       [  4,  21,   2,   1,   1,   6,   1,   6,   7, 135]], dtype=int64)

In [211]:
#by decision tree accuracy is 27 %

In [212]:
img_path='/folder/61515bird.jfif'

In [213]:
img_path

'/folder/61515bird.jfif'

In [214]:

img_arr=cv2.imread('/folder/61515bird.jfif',0)


In [215]:
img_arr

In [216]:
nx, ny, nrgb = img_arr.shape
img_arr2 = img_arr.reshape(1,(nx*ny*nrgb))

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

In [217]:
ans=model.predict(img_arr2)
print(classes[ans[0]])
#RandomForestClassifier

NameError: name 'img_arr2' is not defined